### ISSUE TITLE
NXDN and dPMR descrambler (Question)

### ISSUE THREAD

**Issue by TheDefender44** [f4exb/dsdcc#35]
Hi -
Just like the recently implemented MotoTRBO Basic Privacy feature, do you have any consideration in implementing a similar dPMR and NXDN 15-bit descrambler feature to DSDcc?

Both scrambling methods are very similar and well documented.

Thanks in advance for your input.

**Comment by f4exb** [comment]
> Both scrambling methods are very similar and well documented.

dPMR is from ETSI and I have no doubt it should be well documented. However unlike what you mention in https://github.com/f4exb/sdrangel/issues/548 which this issue is a prerequisite NXDN is not ETSI. It is a proprietary protocol of ICOM and Kenwood. However intentionnally or not a paper has leaked that you can find on the Internet describing the protocol.

I have had no time yet to check this but I am considering it although with not very high priority. You are very well welcome to contribute if you want to see things move a little faster.

**Comment by TheDefender44** [comment]
Thank you very much for your prompt response.

> You are very well welcome to contribute if you want to see things move a little faster.

I would be more than happy to contribute to that effort in any way I can. Unfortunately, I do not have the knowledge to code C/C++. However, I have some dPMR hardware and can provide you with scrambled voice IQ samples with a defined scrambling key for you to run tests if needed. I can run the tests myself as well. I also have in my possession all the technical literature needed for the implementation.

If you are interested, please just let me know and I will be responsive.

**Comment by f4exb** [comment]
This would be indeed a very useful contribution.

**Comment by f4exb** [comment]
There are already too many issues with DMR BP so I am not going to implement any kind of encryption in any mode any way
